export const CATEGORIES = {
  Proteins: [
    { emoji: "🐟", label: "Fish" },
    { emoji: "🥚", label: "Eggs" },
    { emoji: "🍖", label: "Pork" },
    { emoji: "🍗", label: "Chicken" },
    { emoji: "🦐", label: "Shrimp" },
    { emoji: "🥩", label: "Beef" },
    { emoji: "🫘", label: "Beans" },
    { emoji: "🧀", label: "Cheese" },
    { emoji: "🐙", label: "Squid" },
    { emoji: "🦀", label: "Crab" },
  ],
  Vegetables: [
    { emoji: "🍅", label: "Tomato" },
    { emoji: "🧅", label: "Onion" },
    { emoji: "🥦", label: "Broccoli" },
    { emoji: "🫑", label: "Pepper" },
    { emoji: "🥕", label: "Carrot" },
    { emoji: "🥬", label: "Spinach" },
    { emoji: "🍆", label: "Eggplant" },
    { emoji: "🌽", label: "Corn" },
    { emoji: "🥔", label: "Potato" },
    { emoji: "🧄", label: "Garlic" },
  ],
  Fruits: [
    { emoji: "🍋", label: "Lemon" },
    { emoji: "🍌", label: "Banana" },
    { emoji: "🍎", label: "Apple" },
    { emoji: "🍊", label: "Orange" },
    { emoji: "🥑", label: "Avocado" },
    { emoji: "🍇", label: "Grapes" },
    { emoji: "🥭", label: "Mango" },
    { emoji: "🍓", label: "Strawberry" },
  ],
  Grains: [
    { emoji: "🍚", label: "Rice" },
    { emoji: "🍝", label: "Pasta" },
    { emoji: "🍞", label: "Bread" },
    { emoji: "🌾", label: "Flour" },
    { emoji: "🥙", label: "Pita" },
    { emoji: "🌯", label: "Tortilla" },
    { emoji: "🥣", label: "Oats" },
    { emoji: "🫓", label: "Naan" },
  ],
  "Dairy & Pantry": [
    { emoji: "🥛", label: "Milk" },
    { emoji: "🧈", label: "Butter" },
    { emoji: "🫙", label: "Yogurt" },
    { emoji: "🧂", label: "Salt" },
    { emoji: "🫒", label: "Olive Oil" },
    { emoji: "🍯", label: "Honey" },
    { emoji: "🌶️", label: "Chili" },
    { emoji: "🥫", label: "Canned Tomato" },
  ],
};